[build-system]
build-backend = "poetry.core.masonry.api"
requires = [ "poetry-core>=2,<3" ]

[project]
name = "trustgate"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
  { name = "KarthikUdyawar", email = "karthikajitudy@gmail.com" },
]
requires-python = ">=3.10,<4.0"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "alembic>=1.15.1,<2",
  "fastapi>=0.115.11,<0.116",
  "loguru>=0.7.3,<0.8",
  "psycopg2-binary>=2.9.10,<3",
  "pydantic>=2.10.6,<3",
  "pydantic-settings>=2.8.1,<3",
  "pyyaml>=6.0.2,<7",
  "requests>=2.32.3,<3",
  "sqlalchemy>=2.0.39,<3",
]

[tool.poetry]
packages = [
  { include = "constants", from = "src" },
  { include = "controllers", from = "src" },
  { include = "core", from = "src" },
  { include = "models", from = "src" },
  { include = "routes", from = "src" },
  { include = "services", from = "src" },
  { include = "utils", from = "src" },
]

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"
types-pyyaml = "^6.0.12.20241230"
tomli = "^2.2.1"
debugpy = "^1.8.13"
types-requests = "^2.32.0.20250306"
