"""added_scopeEnum_in_role_and_drop_user.

Revision ID: 20f0c87efc58
Revises: 2928c7b64895
Create Date: 2025-05-18 21:59:33.635362

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20f0c87efc58"
down_revision: Union[str, None] = "2928c7b64895"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_is_deleted", table_name="users")
    op.drop_index("ix_users_user_name", table_name="users")
    op.drop_table("users")
    op.add_column(
        "roles", sa.Column("scopes", sa.ARRAY(sa.String()), nullable=False)
    )
    op.create_index(
        "ix_roles_is_deleted", "roles", ["is_deleted"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_roles_is_deleted", table_name="roles")
    op.drop_column("roles", "scopes")
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "user_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "hashed_password",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "INACTIVE", "ACTIVE", "SUSPENDED", name="userstatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_users_user_name", "users", ["user_name"], unique=True)
    op.create_index(
        "ix_users_is_deleted", "users", ["is_deleted"], unique=False
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name="user_roles_role_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_roles_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name="user_roles_pkey"),
    )
    # ### end Alembic commands ###
