"""Add is_deleted to roles table.

Revision ID: 2928c7b64895
Revises: 37cee06974d7
Create Date: 2025-03-31 12:42:50.370196

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2928c7b64895"
down_revision: Union[str, None] = "37cee06974d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roles", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "users", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "roles", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
