"""Added more scope.

Revision ID: 8908867a71ad
Revises: 20f0c87efc58
Create Date: 2025-05-20 01:38:08.730193

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8908867a71ad"
down_revision: Union[str, None] = "20f0c87efc58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
